version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1qwertyu
      MYSQL_DATABASE: poll-app
    ports:
      - "3306:3306"

  server:
    build: ./poll-app-server
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/poll-app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1qwertyu
    depends_on:
      - db
    ports:
      - "8080:8080"

  client:
    build:
      context: ./poll-app-client
      args:
        API_URL: http://server:8080
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "4200:80"
